// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/adapters/postgres"
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/adapters/redis"
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/application"
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/domain"
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/presentation/http"
	"github.com/bshongwe/linkpulse/backend/shared/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*http.Handler, domain.TokenService, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, nil, err
	}
	databaseConfig := &configConfig.Database
	db, err := postgres.NewDB(databaseConfig)
	if err != nil {
		return nil, nil, nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	jwtConfig := configConfig.JWT
	redisConfig := &configConfig.Redis
	client, err := redis.NewClient(redisConfig)
	if err != nil {
		return nil, nil, nil, err
	}
	tokenBlacklist := redis.NewTokenBlacklist(client)
	tokenService := application.NewTokenService(jwtConfig, tokenBlacklist)
	authService := application.NewAuthService(userRepository, tokenService)
	handler := http.NewHandler(authService)
	return handler, tokenService, func() {
	}, nil
}

// wire.go:

// Wire set for Auth service
var Set = wire.NewSet(postgres.NewDB, postgres.NewUserRepository, redis.NewClient, redis.NewTokenBlacklist, application.NewTokenService, application.NewAuthService, http.NewHandler, wire.FieldsOf(new(*config.Config), "Database"), wire.FieldsOf(new(*config.Config), "Redis"), wire.FieldsOf(new(*config.Config), "JWT"))
