// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/adapters/postgres"
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/application"
	"github.com/bshongwe/linkpulse/backend/services/auth/internal/presentation/http"
	"github.com/bshongwe/linkpulse/backend/shared/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*http.Handler, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	databaseConfig := &configConfig.Database
	db, err := postgres.NewDB(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	authService := application.NewAuthService(userRepository)
	handler := http.NewHandler(authService)
	return handler, func() {
	}, nil
}

// wire.go:

// Wire set for Auth service
var Set = wire.NewSet(postgres.NewDB, postgres.NewUserRepository, application.NewAuthService, http.NewHandler, wire.FieldsOf(new(*config.Config), "Database"))
