// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bshongwe/linkpulse/backend/services/shortener/internal/adapters/postgres"
	"github.com/bshongwe/linkpulse/backend/services/shortener/internal/adapters/redis"
	"github.com/bshongwe/linkpulse/backend/services/shortener/internal/application"
	httphandler "github.com/bshongwe/linkpulse/backend/services/shortener/internal/presentation/http"
	"github.com/bshongwe/linkpulse/backend/shared/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*httphandler.ShortenerHandler, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	databaseConfig := &configConfig.Database
	db, err := postgres.NewDB(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	linkRepository := postgres.NewLinkRepository(db)
	redisConfig := &configConfig.Redis
	client, err := redis.NewClient(redisConfig)
	if err != nil {
		return nil, nil, err
	}
	cachePort := redis.NewCache(client)
	shortenerService := application.NewShortenerService(linkRepository, cachePort)
	shortenerHandler := httphandler.NewShortenerHandler(shortenerService)
	return shortenerHandler, func() {}, nil
}

// wire.go:

var Set = wire.NewSet(postgres.NewDB, postgres.NewLinkRepository, redis.NewClient, redis.NewCache, application.NewShortenerService, httphandler.NewShortenerHandler, wire.FieldsOf(new(*config.Config), "Database"), wire.FieldsOf(new(*config.Config), "Redis"))
